name: skin_ai_app
description: A Skin Disease Classification App

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_ml_model_downloader: ^0.1.1
  cloud_firestore: ^4.3.1
  image_picker: ^0.8.5
  google_maps_flutter: ^2.1.8
  http: ^0.13.4
  tflite_flutter: ^0.9.0
  image: ^4.0.15
  flutter_image_compress: ^1.1.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
